server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://payment-mysql:3306/payment_db
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:-truckbites_root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    exchange: truckbites.exchange
    routing-key:
      order-placed: order.placed
      order-paid: order.paid
    queue:
      order-placed: order.placed.queue

razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_TLzX3pgsX3VSku}
  key-secret: ${RAZORPAY_KEY_SECRET:y7oqLKCalRJf5oVTG7hweSKN}

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
