server:
  port: 8087

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    exchange: truckbites.exchange
    routing-key:
      order-placed: order.placed
      order-paid: order.paid
    queue:
      notification: notification.queue

# Mailtrap config is provided by Config Server in notification-service.yml

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
