server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:menu_db;INIT=CREATE SCHEMA IF NOT EXISTS truckbites_menu_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47

eureka:
  client:
    enabled: false
